import argparse
import re
import pysam
import os

parser=argparse.ArgumentParser()

parser.add_argument("-f","--file_in",help="Input bam file name", required=True)
parser.add_argument("-s","--sample_name",help="Sample name", required=True)
parser.add_argument("-c","--coordinates",help="Input file with coordinates", required=True)
parser.add_argument("-o","--file_out",help="Output results file name", default="SpliceVariants_results.tsv")
parser.add_argument("-q","--filter_file",help="File with query names for each primer generated by Filter_RACEbam", required=True)
parser.add_argument("-m","--min_mq",help="Minimum mapping quality to count a read", type=int, default=10)
args=parser.parse_args()

bam_chr=False
in_bamfile=pysam.AlignmentFile(args.file_in, "rb")
if "chr1" in in_bamfile.references:
    bam_chr=True
    
filter_file=open(args.filter_file, "rt")
filter_dict={}
for line in filter_file:
    line_vals=line.strip("\n").split(" ")
    filter_dict[line_vals[0]]=line_vals[1].split(",")
filter_file.close()
    
coordinates_file=open(args.coordinates,'rt')
header=coordinates_file.readline().strip("\n").split("\t")

print_header=["Sample","Variant","Allele","ReadsPerAllele","PercReadsPerAllele"]

print_array=[]
variant_depth_dict={}

for line in coordinates_file:
    line_array=line.strip("\n").split("\t")
    line_dict={}
    for i in range(0,len(header)):
        line_dict[header[i]]=line_array[i]
    """
    VariantName
    PrimerName
    RegionsPresent_Chr
    RegionsPresent_Start
    RegionsPresent_End
    RegionsAbsent_Chr
    RegionsAbsent_Start
    RegionsAbsent_End
    AlleleName
    """
    
    #Find the set of reads with the specified region present
    
    if re.match("chr",line_dict["RegionsPresent_Chr"]) and not(bam_chr):
        line_dict["RegionsPresent_Chr"]=line_dict["RegionsPresent_Chr"][3:]
    elif not(re.match("chr",line_dict["RegionsPresent_Chr"])) and bam_chr:
        line_dict["RegionsPresent_Chr"]="chr"+line_dict["RegionsPresent_Chr"]
        
    if re.match("chr",line_dict["RegionsAbsent_Chr"]) and not(bam_chr):
        line_dict["RegionsAbsent_Chr"]=line_dict["RegionsAbsent_Chr"][3:]
    elif not(re.match("chr",line_dict["RegionsAbsent_Chr"])) and bam_chr:
        line_dict["RegionsAbsent_Chr"]="chr"+line_dict["RegionsAbsent_Chr"]
    
    '''
    if int(line_dict["RegionsPresent_Start"])>int(line_dict["RegionsPresent_End"]):
        start_coord=int(line_dict["RegionsPresent_End"])
        end_coord=int(line_dict["RegionsPresent_Start"])
    else:
        end_coord=int(line_dict["RegionsPresent_End"])
        start_coord=int(line_dict["RegionsPresent_Start"])
    '''
    
    start_coord=int(line_dict["RegionsPresent_Start"])
    end_coord=int(line_dict["RegionsPresent_End"])
    present_fetch=in_bamfile.fetch(contig=line_dict["RegionsPresent_Chr"], start=start_coord, stop=end_coord)
    
    
    
    present_reads=[]
    for each_read in present_fetch:
        if (not each_read.is_duplicate) and\
            each_read.is_mapped and\
            each_read.is_proper_pair and\
            (not each_read.is_qcfail) and\
            (not each_read.is_secondary) and\
            (not each_read.is_supplementary) and\
            (not each_read.is_unmapped) and\
            each_read.mapping_quality>=args.min_mq and\
            each_read.get_overlap(start_coord,end_coord) and\
            each_read.query_name in filter_dict[line_dict["PrimerName"]]:
            present_reads.append(each_read.query_name)
    present_set=set(present_reads)
    
    absent_reads=[]
    if line_dict["RegionsAbsent_Chr"] and line_dict["RegionsAbsent_Start"] and line_dict["RegionsAbsent_End"]:
        start_coord=int(line_dict["RegionsAbsent_Start"])
        end_coord=int(line_dict["RegionsAbsent_End"])
        absent_fetch=in_bamfile.fetch(contig=line_dict["RegionsAbsent_Chr"], start=start_coord, stop=end_coord)
        for each_read in absent_fetch:
            if each_read.get_overlap(start_coord,end_coord):
                absent_reads.append(each_read.query_name)
    absent_set=set(absent_reads)        
    
    allele_count=len(present_set-absent_set)
    
    if line_dict["VariantName"] in variant_depth_dict:
        variant_depth_dict[line_dict["VariantName"]]+=allele_count
    else:
        variant_depth_dict[line_dict["VariantName"]]=allele_count
    
    print_res=[args.sample_name,line_dict["VariantName"],line_dict["AlleleName"],allele_count]
    print_array.append(print_res)
    
if not os.path.exists(args.file_out):
    res_file=open(args.file_out,'wt')
    print("\t".join(print_header),file=res_file)
else:
    res_file=open(args.file_out,'at')
    
for each_res in print_array:
    if variant_depth_dict[each_res[1]]==0:
        each_res.append('0')
    else:
        each_res.append(str(round(each_res[3]*100/variant_depth_dict[each_res[1]],1)))
    each_res[3]=str(each_res[3])
    print("\t".join(each_res),file=res_file)

res_file.close()

coordinates_file.close()
in_bamfile.close()